//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.Users1 = new HashSet<Users>();
        }
    
        public int eventId { get; set; }
        public int capacity { get; set; }
        public string description { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime end { get; set; }
        public bool allDay { get; set; }
        public Nullable<int> classesTypeId { get; set; }
        public int hallId { get; set; }
        public string trainerId { get; set; }
    
        public virtual ClassesType ClassesType { get; set; }
        public virtual Halls Halls { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users1 { get; set; }
    }
}
