//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int productId { get; set; }
        public int orderDetailId { get; set; }
        public int orderId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal unitPrice { get; set; }
        public short quantity { get; set; }
        public float discount { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
