//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int paymentDetailsId { get; set; }
        public int orderId { get; set; }
        public int paymentDataId { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public decimal value { get; set; }
    
        public virtual Orders Order { get; set; }
        public virtual PaymentData PaymentData { get; set; }
    }
}
