// <auto-generated />
namespace Limitless.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetAspNetUsertableasdefaulttoforeignkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetAspNetUsertableasdefaulttoforeignkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201611291804279_Set AspNetUser table as default to foreign key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
