// <auto-generated />
namespace Limitless.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateLogTable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateLogTable2));
        
        string IMigrationMetadata.Id
        {
            get { return "201612182054573_updateLogTable2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
